### 1. Отримати всі відправлення
GET http://localhost:5211/postings

### 2. Отримати відправлення за id
GET http://localhost:5211/postings/1

### 3. Додати нове відправлення
POST http://localhost:5211/postings
Content-Type: application/json

{
  "from": "Рівне",
  "to": "Київ",
  "content": "Посилка з книгами",
  "deliveryType": "Express",
  "weight": 3,
  "width": 25,
  "height": 30,
  "depth": 10,
  "value": 800
}

### 4. Оновити відправлення
PUT http://localhost:5211/postings/1
Content-Type: application/json

{
  "id": 1,
  "from": "Рівне",
  "to": "Львів",
  "content": "Термінові речі",
  "deliveryType": "Courier",
  "weight": 2,
  "width": 20,
  "height": 30,
  "depth": 15,
  "value": 600
}

### 5. Видалити відправлення
DELETE http://localhost:5211/postings/1

### 6. Перевірити видалення
GET http://localhost:5211/postings/1
